language: node_js
node_js:
- "12"
cache:
  directories:
  - node_modules
env:
  global:
  - PATH=$HOME/.wantedly/bin:$PATH
install:
- npm install
script:
- npm run build
- npm test
deploy:
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: 'web-ext-artifacts/*'
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: npm run publish:chrome
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: npm run publish:firefox
  on:
    tags: true
